# Generated by Django 6.0.5 on 2026-05-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='user', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='from_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='billing.device'),
        ),
        migrations.AlterField(
            model_name='call',
            name='to_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='billing.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Мобильный'), ('home', 'Домашний')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='call',
            table='calls',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='tariff',
            table='tariffs',
        ),
    ]
