# Generated by Django 6.0.5 on 2026-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_client_is_admin_client_password_client_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_minute',
            field=models.FloatField(default=1.0),
        ),
    ]
